import Head from 'next/head'
import { Hero } from '../components/home/01-hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>The Goombahs | NFT Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
      </main>
    </>
  )
}
