import Head from 'next/head'
import { Hero } from '../components/home/01-hero'
import { Commission } from '../components/home/02-commission'
import { Muscle } from '../components/home/03-muscle'
import { Roadmap } from '../components/home/04-roadmap'
import { Contact } from '../components/home/05-contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>The Goombahs | NFT Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Commission />
        <Muscle />
        <Roadmap />
        <Contact />
      </main>
    </>
  )
}
